### ISSUE TITLE
The "Getting started" instructions aren't quite right

### ISSUE THREAD

**Issue by haydn** [sketchbook-js/website#2]
The instructions don't take into account the need to specify a design file and the design file gets generated at `sketchbook/example.json`:

![image](https://user-images.githubusercontent.com/27211/117382493-fdb1c680-af21-11eb-8916-8fc681ad3901.png)

**Comment by Mxchaeltrxn** [comment]
@haydn Updated in [this commit](https://github.com/sketchbook-js/website/commit/4c3f752dde29e8b70771f8d8440e6c63ab1cd52f).

**Comment by haydn** [comment]
@Mxchaeltrxn This isn't true:

![image](https://user-images.githubusercontent.com/27211/117568517-07931f80-b104-11eb-9ae3-178a8e35a95f.png)

The start command requires the user to provide the design file:

https://github.com/sketchbook-js/sketchbook/blob/master/cli/index.js#L71-L81
