### ISSUE TITLE
Add support for dark mode

### ISSUE THREAD

**Issue by haydn** [sketchbook-js/website#4]
If the user has `prefers-color-scheme: dark`, respect that.

**Comment by Mxchaeltrxn** [comment]
@haydn I'm willing to take this one on once the other pull requests are done.

Creating a theme is a bit beyond me but I can try and make and implement one. Do you have any tips to help me get started?

**Comment by haydn** [comment]
@Mxchaeltrxn Good choice! This should be a pretty easy win because we don't have too many colours our CSS.

I think the [prefers-color-scheme media feature](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) combined with the [color-scheme property](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme) will get you most of the way there:

```css
@media (prefers-color-scheme: dark) {
  :root {
    color-scheme: dark light;
  }
}
```

To test you can emulate light/dark mode with the Chrome DevTools:

![image](https://user-images.githubusercontent.com/27211/123411623-fd65ab80-d5f3-11eb-8505-6871cfe02fad.png)
